Trigger CI because last commit's Build had internal problems
http://tekton-dashboard.staging-2b.internal.ingress.vtex.io/#/namespaces/faststore-build/pipelineruns/build-pipeline-run-tb4wf?pipelineTask=build&step=deploy-functions

```
+ cd /workspace/build/feat/style-plp/vtex-sites/base.store
+ '[' -f /tekton/results/conclusion ]
+ cat /tekton/results/conclusion
+ '[' success '=' failure ]
+ echo 'Running sfj-functions'
Running sfj-functions
+ sfj-functions deploy /workspace/build/feat/style-plp/vtex-sites/base.store vtex-sites/base.store
Creating bundle for: vtex-sites/base.store at /workspace/build/feat/style-plp/vtex-sites/base.store
Packing the final bundle
Adding Function Framework: runtime.js
Adding Gatsby Function Manifest: manifest.json
Adding function: graphql.js
Final Zipped bundle: 784.68kB
Function we hash: 498b5f375ea91dd9ca00d1aef2ac6c31
Getting or creating lambda...
Trying to create function we...
Function we created
Setting up API Gateway
API Gateway already exists, id: 3szm9ug7m3
Trying to get integrations with Lambda arn:aws:lambda:us-east-1:558830342743:function:sfj-498b5f375ea91dd9ca00d1aef2ac6c31
TooManyRequestsException: Too Many Requests
    at Object.extractError (/home/node/app/dist/builder.js:16590:27)
    at Request.extractError (/home/node/app/dist/builder.js:16946:8)
    at Request.callListeners (/home/node/app/dist/builder.js:19851:20)
    at Request.emit (/home/node/app/dist/builder.js:19823:10)
    at Request.emit (/home/node/app/dist/builder.js:18457:14)
    at Request.transition (/home/node/app/dist/builder.js:17791:10)
    at AcceptorStateMachine.runTo (/home/node/app/dist/builder.js:24794:12)
    at /home/node/app/dist/builder.js:24806:10
    at Request.<anonymous> (/home/node/app/dist/builder.js:17807:9)
    at Request.<anonymous> (/home/node/app/dist/builder.js:18459:12) {
  code: 'TooManyRequestsException',
  time: 2022-01-21T18:30:28.824Z,
  requestId: '6934e621-ef86-44e6-a99f-bc465acfc183',
  statusCode: 429,
  retryable: true
}
+ url=
+ '[' 0 ]
+ '[' -z  ]
```